name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . --file stable/Dockerfile --tag omercnet/flutter:stable --tag omercnet/flutter
          docker build . --file beta/Dockerfile --tag omercnet/flutter:beta
          docker build . --file dev/Dockerfile --tag omercnet/flutter:dev
